/**
 * Created by andreleite on 01/10/17.
 */
@IsTest
private class ClubeServicoTest {

	@IsTest static void testGetServico() {
		System.assertEquals(true, false, 'Erro force');
	}

	@IsTest static void testObterClube() {

	}

	@IsTest static void testObterSessaoCaixa() {

	}

	@IsTest static void testCriarSessao() {

	}

	@IsTest static void testIsVagaMesa() {

	}

	@IsTest static void testAddJogador() {

	}

	@IsTest static void testDesativarJogadorMesa() {

	}

	@IsTest static void testDesativarJogadorMesa2() {

	}

	@IsTest static void testDesativarJogadorMesa3() {

	}

	@IsTest static void testAtualizarSessaoCaixa() {

	}

	@IsTest static void testObterMesaOption() {

	}

	@IsTest static void testObterSessoesDealerAberta() {

	}

	@IsTest static void testCalcTaxa() {

	}

	@IsTest static void testCalcTaxa2() {

	}

	@IsTest static void testObterFilaClube() {

	}
}